-- head: 0001
-- generated by `python -m insightminer.db.schema_dump`; do not edit by hand
CREATE TABLE alembic_version ( version_num VARCHAR(32) NOT NULL, CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num) );
CREATE TABLE authors ( pk INTEGER NOT NULL, author_fullname TEXT NOT NULL, name TEXT NOT NULL, first_seen_at INTEGER NOT NULL, last_seen_at INTEGER NOT NULL, post_count INTEGER DEFAULT 0 NOT NULL, comment_count INTEGER DEFAULT 0 NOT NULL, CONSTRAINT pk_authors PRIMARY KEY (pk), CONSTRAINT uq_authors_author_fullname UNIQUE (author_fullname) );
CREATE TABLE backups ( pk INTEGER NOT NULL, path TEXT NOT NULL, sha256 TEXT NOT NULL, size_bytes INTEGER NOT NULL, integrity TEXT NOT NULL, kind TEXT NOT NULL, created_at INTEGER NOT NULL, schema_rev TEXT, table_counts_json TEXT, CONSTRAINT pk_backups PRIMARY KEY (pk), CONSTRAINT uq_backups_path UNIQUE (path) );
CREATE TABLE comment_more ( pk INTEGER NOT NULL, post_pk INTEGER NOT NULL, parent_comment_pk INTEGER, count INTEGER NOT NULL, CONSTRAINT pk_comment_more PRIMARY KEY (pk), CONSTRAINT fk_comment_more_post_pk_posts FOREIGN KEY(post_pk) REFERENCES posts (pk) ON DELETE CASCADE );
CREATE TABLE comments ( pk INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, reddit_id TEXT NOT NULL, fullname TEXT NOT NULL, post_pk INTEGER NOT NULL, parent_fullname TEXT NOT NULL, parent_comment_pk INTEGER, author TEXT, author_fullname TEXT, author_is_bot BOOLEAN DEFAULT 0 NOT NULL, body TEXT, body_html TEXT, created_utc INTEGER NOT NULL, edited_utc INTEGER, score INTEGER DEFAULT 0 NOT NULL, depth INTEGER DEFAULT 0 NOT NULL, permalink TEXT, is_submitter BOOLEAN DEFAULT 0 NOT NULL, stickied BOOLEAN DEFAULT 0 NOT NULL, distinguished TEXT, content_state TEXT DEFAULT 'live' NOT NULL, author_state TEXT DEFAULT 'known' NOT NULL, misses INTEGER DEFAULT 0 NOT NULL, scrubbed_at INTEGER, first_seen_at INTEGER NOT NULL, last_fetched_at INTEGER NOT NULL, source TEXT NOT NULL, normalizer_version INTEGER NOT NULL, raw_json TEXT NOT NULL, CONSTRAINT ck_comments_author_state CHECK (author_state IN ('known', 'account_deleted')), CONSTRAINT ck_comments_content_state CHECK (content_state IN ('live', 'deleted_by_author', 'removed_by_moderator', 'removed_by_reddit', 'gone_unconfirmed', 'gone')), CONSTRAINT fk_comments_post_pk_posts FOREIGN KEY(post_pk) REFERENCES posts (pk), CONSTRAINT uq_comments_reddit_id UNIQUE (reddit_id) );
CREATE VIRTUAL TABLE comments_fts USING fts5( body, author, content='comments_live', content_rowid='pk', tokenize='porter unicode61');
CREATE TABLE item_snapshots ( pk INTEGER NOT NULL, item_pk INTEGER NOT NULL, kind TEXT NOT NULL, fetched_at INTEGER NOT NULL, score INTEGER, num_comments INTEGER, upvote_ratio FLOAT, CONSTRAINT pk_item_snapshots PRIMARY KEY (pk), CONSTRAINT ck_item_snapshots_kind CHECK (kind IN ('post', 'comment')) );
CREATE TABLE post_sources ( pk INTEGER NOT NULL, post_pk INTEGER NOT NULL, source_type TEXT NOT NULL, source_pk INTEGER NOT NULL, first_seen_at INTEGER NOT NULL, CONSTRAINT pk_post_sources PRIMARY KEY (pk), CONSTRAINT ck_post_sources_source_type CHECK (source_type IN ('subreddit', 'search')), CONSTRAINT fk_post_sources_post_pk_posts FOREIGN KEY(post_pk) REFERENCES posts (pk) ON DELETE CASCADE, CONSTRAINT uq_post_sources_identity UNIQUE (post_pk, source_type, source_pk) );
CREATE TABLE post_themes ( pk INTEGER NOT NULL, post_pk INTEGER NOT NULL, theme_pk INTEGER NOT NULL, rule_pk INTEGER NOT NULL, matched_field TEXT NOT NULL, tagged_at INTEGER NOT NULL, CONSTRAINT pk_post_themes PRIMARY KEY (pk), CONSTRAINT fk_post_themes_post_pk_posts FOREIGN KEY(post_pk) REFERENCES posts (pk) ON DELETE CASCADE, CONSTRAINT fk_post_themes_rule_pk_theme_rules FOREIGN KEY(rule_pk) REFERENCES theme_rules (pk) ON DELETE CASCADE, CONSTRAINT fk_post_themes_theme_pk_themes FOREIGN KEY(theme_pk) REFERENCES themes (pk) ON DELETE CASCADE, CONSTRAINT uq_post_themes_identity UNIQUE (post_pk, theme_pk, rule_pk, matched_field) );
CREATE TABLE posts ( pk INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, reddit_id TEXT NOT NULL, fullname TEXT NOT NULL, subreddit_pk INTEGER NOT NULL, subreddit_id TEXT, author TEXT, author_fullname TEXT, author_flair_text TEXT, author_is_bot BOOLEAN DEFAULT 0 NOT NULL, title TEXT, selftext TEXT, selftext_html TEXT, url TEXT, domain TEXT, permalink TEXT, created_utc INTEGER NOT NULL, edited_utc INTEGER, score INTEGER DEFAULT 0 NOT NULL, upvote_ratio FLOAT, num_comments INTEGER DEFAULT 0 NOT NULL, link_flair_text TEXT, over_18 BOOLEAN DEFAULT 0 NOT NULL, spoiler BOOLEAN DEFAULT 0 NOT NULL, is_self BOOLEAN DEFAULT 0 NOT NULL, is_video BOOLEAN DEFAULT 0 NOT NULL, is_gallery BOOLEAN DEFAULT 0 NOT NULL, post_hint TEXT, locked BOOLEAN DEFAULT 0 NOT NULL, stickied BOOLEAN DEFAULT 0 NOT NULL, archived BOOLEAN DEFAULT 0 NOT NULL, distinguished TEXT, crosspost_parent TEXT, num_crossposts INTEGER DEFAULT 0 NOT NULL, removed_by_category TEXT, content_state TEXT DEFAULT 'live' NOT NULL, author_state TEXT DEFAULT 'known' NOT NULL, misses INTEGER DEFAULT 0 NOT NULL, scrubbed_at INTEGER, first_seen_at INTEGER NOT NULL, last_fetched_at INTEGER NOT NULL, comments_fetched_at INTEGER, comments_captured INTEGER DEFAULT 0 NOT NULL, comments_complete BOOLEAN DEFAULT 0 NOT NULL, more_skipped BOOLEAN DEFAULT 0 NOT NULL, more_skipped_count INTEGER DEFAULT 0 NOT NULL, more_skipped_reason TEXT, next_check_at INTEGER NOT NULL, check_stage INTEGER DEFAULT 0 NOT NULL, source TEXT NOT NULL, normalizer_version INTEGER NOT NULL, raw_json TEXT NOT NULL, CONSTRAINT ck_posts_author_state CHECK (author_state IN ('known', 'account_deleted')), CONSTRAINT ck_posts_content_state CHECK (content_state IN ('live', 'deleted_by_author', 'removed_by_moderator', 'removed_by_reddit', 'gone_unconfirmed', 'gone')), CONSTRAINT fk_posts_subreddit_pk_subreddits FOREIGN KEY(subreddit_pk) REFERENCES subreddits (pk), CONSTRAINT uq_posts_reddit_id UNIQUE (reddit_id) );
CREATE VIRTUAL TABLE posts_fts USING fts5( title, selftext, author, content='posts_live', content_rowid='pk', tokenize='porter unicode61');
CREATE TABLE raw_rejects ( pk INTEGER NOT NULL, run_pk INTEGER NOT NULL, raw_json TEXT NOT NULL, error TEXT NOT NULL, created_at INTEGER NOT NULL, CONSTRAINT pk_raw_rejects PRIMARY KEY (pk), CONSTRAINT fk_raw_rejects_run_pk_runs FOREIGN KEY(run_pk) REFERENCES runs (pk) ON DELETE CASCADE );
CREATE TABLE run_subreddits ( pk INTEGER NOT NULL, run_pk INTEGER NOT NULL, subreddit_pk INTEGER NOT NULL, pages INTEGER DEFAULT 0 NOT NULL, items_seen INTEGER DEFAULT 0 NOT NULL, new_items INTEGER DEFAULT 0 NOT NULL, updated_items INTEGER DEFAULT 0 NOT NULL, stop_reason TEXT, error TEXT, CONSTRAINT pk_run_subreddits PRIMARY KEY (pk), CONSTRAINT ck_run_subreddits_stop_reason CHECK (stop_reason IN ('exhausted', 'cap', 'error')), CONSTRAINT fk_run_subreddits_run_pk_runs FOREIGN KEY(run_pk) REFERENCES runs (pk) ON DELETE CASCADE, CONSTRAINT fk_run_subreddits_subreddit_pk_subreddits FOREIGN KEY(subreddit_pk) REFERENCES subreddits (pk), CONSTRAINT uq_run_subreddits_identity UNIQUE (run_pk, subreddit_pk) );
CREATE TABLE runs ( pk INTEGER NOT NULL, kind TEXT NOT NULL, "trigger" TEXT NOT NULL, status TEXT NOT NULL, created_at INTEGER NOT NULL, started_at INTEGER, finished_at INTEGER, heartbeat_at INTEGER, pid INTEGER, stage TEXT, options_json TEXT, counters_json TEXT, api_requests INTEGER DEFAULT 0 NOT NULL, app_version TEXT, praw_version TEXT, schema_rev TEXT, settings_fingerprint TEXT, error TEXT, log_path TEXT, purge_counts_json TEXT, CONSTRAINT pk_runs PRIMARY KEY (pk), CONSTRAINT ck_runs_status CHECK (status IN ('queued', 'running', 'ok', 'partial', 'failed', 'rate_limited', 'skipped_locked', 'crashed', 'cancelled')), CONSTRAINT ck_runs_trigger CHECK (trigger IN ('cli', 'ui', 'schedule')) );
CREATE TABLE searches ( pk INTEGER NOT NULL, workspace_pk INTEGER NOT NULL, "query" TEXT NOT NULL, scope TEXT DEFAULT 'all' NOT NULL, sort TEXT DEFAULT 'new' NOT NULL, time_filter TEXT DEFAULT 'week' NOT NULL, enabled BOOLEAN DEFAULT 1 NOT NULL, last_run_at INTEGER, status TEXT, CONSTRAINT pk_searches PRIMARY KEY (pk), CONSTRAINT fk_searches_workspace_pk_workspaces FOREIGN KEY(workspace_pk) REFERENCES workspaces (pk) );
CREATE TABLE subreddits ( pk INTEGER NOT NULL, workspace_pk INTEGER NOT NULL, name_lower TEXT NOT NULL, display_name TEXT NOT NULL, subreddit_id TEXT, subreddit_type TEXT, subscribers INTEGER, over18 BOOLEAN, quarantine BOOLEAN, enabled BOOLEAN DEFAULT 1 NOT NULL, comment_mode TEXT DEFAULT 'full' NOT NULL, added_at INTEGER NOT NULL, watermark_created_utc INTEGER, last_complete_poll_at INTEGER, status TEXT DEFAULT 'ok' NOT NULL, last_error TEXT, consecutive_failures INTEGER DEFAULT 0 NOT NULL, gap_suspected_at INTEGER, CONSTRAINT pk_subreddits PRIMARY KEY (pk), CONSTRAINT ck_subreddits_status CHECK (status IN ('ok', 'forbidden', 'not_found', 'redirect', 'quarantined', 'error')), CONSTRAINT fk_subreddits_workspace_pk_workspaces FOREIGN KEY(workspace_pk) REFERENCES workspaces (pk), CONSTRAINT uq_subreddits_workspace_name_lower UNIQUE (workspace_pk, name_lower), CONSTRAINT uq_subreddits_workspace_subreddit_id UNIQUE (workspace_pk, subreddit_id) );
CREATE TABLE theme_rules ( pk INTEGER NOT NULL, theme_pk INTEGER NOT NULL, rule_group TEXT NOT NULL, kind TEXT NOT NULL, pattern TEXT NOT NULL, scope TEXT DEFAULT 'any' NOT NULL, case_sensitive BOOLEAN DEFAULT 0 NOT NULL, whole_word BOOLEAN DEFAULT 0 NOT NULL, enabled BOOLEAN DEFAULT 1 NOT NULL, CONSTRAINT pk_theme_rules PRIMARY KEY (pk), CONSTRAINT ck_theme_rules_kind CHECK (kind IN ('keyword', 'regex', 'flair', 'subreddit')), CONSTRAINT ck_theme_rules_rule_group CHECK (rule_group IN ('match', 'exclude', 'only_in')), CONSTRAINT ck_theme_rules_scope CHECK (scope IN ('title', 'body', 'comments', 'any')), CONSTRAINT fk_theme_rules_theme_pk_themes FOREIGN KEY(theme_pk) REFERENCES themes (pk) ON DELETE CASCADE );
CREATE TABLE themes ( pk INTEGER NOT NULL, workspace_pk INTEGER NOT NULL, name TEXT NOT NULL, slug TEXT NOT NULL, color TEXT, description TEXT, enabled BOOLEAN DEFAULT 1 NOT NULL, rules_hash TEXT, tagged_hash TEXT, CONSTRAINT pk_themes PRIMARY KEY (pk), CONSTRAINT fk_themes_workspace_pk_workspaces FOREIGN KEY(workspace_pk) REFERENCES workspaces (pk), CONSTRAINT uq_themes_workspace_name UNIQUE (workspace_pk, name), CONSTRAINT uq_themes_workspace_slug UNIQUE (workspace_pk, slug) );
CREATE TABLE ui_state ( "key" TEXT NOT NULL, value TEXT NOT NULL, updated_at INTEGER NOT NULL, CONSTRAINT pk_ui_state PRIMARY KEY ("key") );
CREATE TABLE workspaces ( pk INTEGER NOT NULL, slug TEXT NOT NULL, name TEXT NOT NULL, description TEXT, ranking TEXT DEFAULT 'distinct_authors' NOT NULL, digest_settings_json TEXT, created_at INTEGER NOT NULL, CONSTRAINT pk_workspaces PRIMARY KEY (pk), CONSTRAINT uq_workspaces_slug UNIQUE (slug) );
CREATE VIEW comments_live AS SELECT pk, body, author FROM comments WHERE content_state = 'live';
CREATE VIEW posts_live AS SELECT pk, title, selftext, author FROM posts WHERE content_state = 'live';
CREATE INDEX ix_comments_author_fullname ON comments (author_fullname);
CREATE INDEX ix_comments_post_pk_parent_comment_pk ON comments (post_pk, parent_comment_pk);
CREATE INDEX ix_item_snapshots_item_pk_fetched_at ON item_snapshots (item_pk, fetched_at);
CREATE INDEX ix_post_themes_theme_pk ON post_themes (theme_pk);
CREATE INDEX ix_posts_author_fullname ON posts (author_fullname);
CREATE INDEX ix_posts_content_state ON posts (content_state);
CREATE INDEX ix_posts_next_check_at ON posts (next_check_at);
CREATE INDEX ix_posts_subreddit_pk_created_utc ON posts (subreddit_pk, created_utc);
CREATE INDEX ix_searches_workspace_pk ON searches (workspace_pk);
CREATE INDEX ix_subreddits_workspace_pk ON subreddits (workspace_pk);
CREATE INDEX ix_themes_workspace_pk ON themes (workspace_pk);
CREATE TRIGGER comments_fts_ad AFTER DELETE ON comments WHEN old.content_state = 'live' BEGIN INSERT INTO comments_fts(comments_fts, rowid, body, author) VALUES ('delete', old.pk, old.body, old.author); END;
CREATE TRIGGER comments_fts_ai AFTER INSERT ON comments WHEN new.content_state = 'live' BEGIN INSERT INTO comments_fts(rowid, body, author) VALUES (new.pk, new.body, new.author); END;
CREATE TRIGGER comments_fts_au AFTER UPDATE OF body, author, content_state ON comments BEGIN INSERT INTO comments_fts(comments_fts, rowid, body, author) SELECT 'delete', old.pk, old.body, old.author WHERE old.content_state = 'live'; INSERT INTO comments_fts(rowid, body, author) SELECT new.pk, new.body, new.author WHERE new.content_state = 'live'; END;
CREATE TRIGGER posts_fts_ad AFTER DELETE ON posts WHEN old.content_state = 'live' BEGIN INSERT INTO posts_fts(posts_fts, rowid, title, selftext, author) VALUES ('delete', old.pk, old.title, old.selftext, old.author); END;
CREATE TRIGGER posts_fts_ai AFTER INSERT ON posts WHEN new.content_state = 'live' BEGIN INSERT INTO posts_fts(rowid, title, selftext, author) VALUES (new.pk, new.title, new.selftext, new.author); END;
CREATE TRIGGER posts_fts_au AFTER UPDATE OF title, selftext, author, content_state ON posts BEGIN INSERT INTO posts_fts(posts_fts, rowid, title, selftext, author) SELECT 'delete', old.pk, old.title, old.selftext, old.author WHERE old.content_state = 'live'; INSERT INTO posts_fts(rowid, title, selftext, author) SELECT new.pk, new.title, new.selftext, new.author WHERE new.content_state = 'live'; END;
-- COLUMN COMMENTS
-- authors.pk: Surrogate key.
-- authors.author_fullname: Author fullname (t2_...).
-- authors.name: Author name as last seen.
-- authors.first_seen_at: Epoch seconds of the first captured item.
-- authors.last_seen_at: Epoch seconds of the most recent captured item.
-- authors.post_count: Captured posts; checked against COUNT(*) by invariant.
-- authors.comment_count: Captured comments; checked against COUNT(*) by invariant.
-- backups.pk: Surrogate key.
-- backups.path: Absolute path of the backup file.
-- backups.sha256: SHA-256 of the file after it was written.
-- backups.size_bytes: File size.
-- backups.integrity: PRAGMA integrity_check result on the copy ('ok' or text).
-- backups.kind: daily, weekly, pre-migrate, manual or export.
-- backups.created_at: Epoch seconds the backup finished.
-- backups.schema_rev: Alembic revision of the database at backup time.
-- backups.table_counts_json: Row counts per table at backup time as JSON, for restore verification.
-- comment_more.pk: Surrogate key.
-- comment_more.post_pk: Owning post row.
-- comment_more.parent_comment_pk: Comment the stub hangs under; NULL when directly under the post. No FK.
-- comment_more.count: Number of replies Reddit reported behind the stub.
-- comments.pk: Surrogate key; also the FTS rowid. AUTOINCREMENT.
-- comments.reddit_id: Reddit base36 id (without t1_ prefix).
-- comments.fullname: Reddit fullname (t1_ + reddit_id).
-- comments.post_pk: Owning post row.
-- comments.parent_fullname: Raw parent fullname (t3_ for top level, t1_ otherwise).
-- comments.parent_comment_pk: Parent comment row when captured; NULL at top level or under a stub. No FK.
-- comments.author: Author name; NULL once scrubbed or account deleted.
-- comments.author_fullname: Author fullname (t2_...); NULL once scrubbed or account deleted.
-- comments.author_is_bot: Heuristic or confirmed bot author; excluded from themes and digest.
-- comments.body: Markdown body; NULL once scrubbed.
-- comments.body_html: Body rendered and sanitised at ingest; NULL once scrubbed.
-- comments.created_utc: Epoch seconds the comment was created (Reddit clock).
-- comments.edited_utc: Epoch seconds of the last edit; NULL when never edited.
-- comments.score: Net score at last fetch.
-- comments.depth: Nesting depth (0 = top level).
-- comments.permalink: Reddit permalink path; NULL once scrubbed.
-- comments.is_submitter: Author is the post author.
-- comments.stickied: Pinned by moderators.
-- comments.distinguished: Upstream distinguish stored raw (moderator, admin, ...).
-- comments.content_state: Derived content state; see CONTENT_STATES. Only live rows are indexed.
-- comments.author_state: Derived author state; see AUTHOR_STATES.
-- comments.misses: Consecutive reconcile passes in which info() omitted the item.
-- comments.scrubbed_at: Epoch seconds when content and author columns were nulled.
-- comments.first_seen_at: Epoch seconds of first capture; never updated.
-- comments.last_fetched_at: Epoch seconds of the last successful fetch.
-- comments.source: Ingest path of the last write (comments, info, ...).
-- comments.normalizer_version: Version of the JSON-to-columns code that wrote the row.
-- comments.raw_json: Canonical raw JSON for reprocessing; replaced by a tombstone on scrub.
-- item_snapshots.pk: Surrogate key.
-- item_snapshots.item_pk: posts.pk or comments.pk depending on kind. No FK.
-- item_snapshots.kind: post or comment.
-- item_snapshots.fetched_at: Epoch seconds of the fetch that produced the snapshot.
-- item_snapshots.score: Score at fetch time.
-- item_snapshots.num_comments: Comment count at fetch time (posts only).
-- item_snapshots.upvote_ratio: Upvote ratio at fetch time (posts only).
-- post_sources.pk: Surrogate key.
-- post_sources.post_pk: The post.
-- post_sources.source_type: Kind of source; see SOURCE_TYPES.
-- post_sources.source_pk: subreddits.pk or searches.pk depending on source_type.
-- post_sources.first_seen_at: Epoch seconds this source first delivered the post.
-- post_themes.pk: Surrogate key.
-- post_themes.post_pk: Tagged post.
-- post_themes.theme_pk: Theme applied.
-- post_themes.rule_pk: Rule that matched.
-- post_themes.matched_field: Field the rule matched (title, body, comments, ...).
-- post_themes.tagged_at: Epoch seconds the tag was written.
-- posts.pk: Surrogate key; also the FTS rowid. AUTOINCREMENT.
-- posts.reddit_id: Reddit base36 id (without t3_ prefix).
-- posts.fullname: Reddit fullname (t3_ + reddit_id).
-- posts.subreddit_pk: Owning subreddit row.
-- posts.subreddit_id: Subreddit fullname (t5_...) as reported on the item.
-- posts.author: Author name; NULL once scrubbed or account deleted.
-- posts.author_fullname: Author fullname (t2_...); NULL once scrubbed or account deleted.
-- posts.author_flair_text: Author flair in this subreddit; NULL once scrubbed.
-- posts.author_is_bot: Heuristic or confirmed bot author; excluded from themes and digest.
-- posts.title: Title; NULL once scrubbed.
-- posts.selftext: Markdown body (empty for link posts); NULL once scrubbed.
-- posts.selftext_html: Body rendered and sanitised at ingest; NULL once scrubbed.
-- posts.url: Link target; NULL once scrubbed.
-- posts.domain: Domain of url (self.<sub> for self posts); NULL once scrubbed.
-- posts.permalink: Reddit permalink path (contains the title slug); NULL once scrubbed.
-- posts.created_utc: Epoch seconds the post was created (Reddit clock).
-- posts.edited_utc: Epoch seconds of the last edit; NULL when never edited.
-- posts.score: Net score at last fetch.
-- posts.upvote_ratio: Upvote ratio 0..1 at last fetch.
-- posts.num_comments: Comment count reported by Reddit at last fetch.
-- posts.link_flair_text: Post flair text.
-- posts.over_18: Marked NSFW.
-- posts.spoiler: Marked spoiler.
-- posts.is_self: Text post (no link).
-- posts.is_video: Reddit-hosted video.
-- posts.is_gallery: Image gallery post.
-- posts.post_hint: Upstream media hint stored raw (image, link, hosted:video, ...).
-- posts.locked: Comments locked.
-- posts.stickied: Pinned by moderators; excluded from sweep stop logic.
-- posts.archived: Archived (no new comments).
-- posts.distinguished: Upstream distinguish stored raw (moderator, admin, ...).
-- posts.crosspost_parent: Fullname of the crosspost parent; its text is never stored.
-- posts.num_crossposts: Crosspost count.
-- posts.removed_by_category: Upstream removal category stored raw (moderator, reddit, deleted, ...).
-- posts.content_state: Derived content state; see CONTENT_STATES. Only live rows are indexed.
-- posts.author_state: Derived author state; see AUTHOR_STATES.
-- posts.misses: Consecutive reconcile passes in which info() omitted the item.
-- posts.scrubbed_at: Epoch seconds when content and author columns were nulled.
-- posts.first_seen_at: Epoch seconds of first capture; never updated.
-- posts.last_fetched_at: Epoch seconds of the last successful fetch.
-- posts.comments_fetched_at: Epoch seconds of the last comment-tree fetch.
-- posts.comments_captured: Comments stored from the last tree fetch.
-- posts.comments_complete: 1 when the tree fetch succeeded and replace_more skipped nothing.
-- posts.more_skipped: 1 when at least one 'more' stub was left unexpanded.
-- posts.more_skipped_count: Comments left unexpanded (sum of stub counts).
-- posts.more_skipped_reason: Why stubs were skipped (per-post cap, budget, error).
-- posts.next_check_at: Epoch seconds the revisit ladder makes this post due; NOT NULL by design.
-- posts.check_stage: Revisit ladder stage reached (0 = discovered).
-- posts.source: Ingest path of the last write (e.g. subreddit_new, comments).
-- posts.normalizer_version: Version of the JSON-to-columns code that wrote the row.
-- posts.raw_json: Canonical raw JSON for reprocessing; replaced by a tombstone on scrub.
-- raw_rejects.pk: Surrogate key.
-- raw_rejects.run_pk: Run that saw it.
-- raw_rejects.raw_json: The rejected item.
-- raw_rejects.error: Why it was rejected.
-- raw_rejects.created_at: Epoch seconds; rows older than 30 days are purged.
-- run_subreddits.pk: Surrogate key.
-- run_subreddits.run_pk: The run.
-- run_subreddits.subreddit_pk: The subreddit swept.
-- run_subreddits.pages: Listing pages fetched.
-- run_subreddits.items_seen: Items seen in the listing.
-- run_subreddits.new_items: Posts inserted.
-- run_subreddits.updated_items: Posts updated.
-- run_subreddits.stop_reason: Why paging stopped; see STOP_REASONS. NULL while in progress.
-- run_subreddits.error: Error message when stop_reason=error.
-- runs.pk: Surrogate key.
-- runs.kind: Command kind (run, fetch, comments, reconcile, ...).
-- runs.trigger: Who started it; see RUN_TRIGGERS.
-- runs.status: Lifecycle state; see RUN_STATUSES.
-- runs.created_at: Epoch seconds the row was created (queued or started).
-- runs.started_at: Epoch seconds the process took the lock; NULL while queued.
-- runs.finished_at: Epoch seconds of completion; NULL while running.
-- runs.heartbeat_at: Epoch seconds of the last heartbeat; stale after 3 minutes.
-- runs.pid: Process id of the runner.
-- runs.stage: Current stage carried by the heartbeat (e.g. rate_wait:37s).
-- runs.options_json: Requested options as JSON, including the written reason for any bypass.
-- runs.counters_json: Outcome counters as JSON (new, updated, scrubbed, unknown_enum_values...).
-- runs.api_requests: HTTP requests counted by our own session hook.
-- runs.app_version: insightminer version.
-- runs.praw_version: PRAW version.
-- runs.schema_rev: Alembic revision at run time.
-- runs.settings_fingerprint: Hash of the resolved non-secret settings.
-- runs.error: Terminal error message, if any.
-- runs.log_path: Path of the run's log file.
-- runs.purge_counts_json: Rows purged per table as JSON, so the row-count invariant can read them.
-- searches.pk: Surrogate key.
-- searches.workspace_pk: Owning workspace.
-- searches.query: Reddit search query.
-- searches.scope: 'all' or a comma-separated list of subreddit names to search within.
-- searches.sort: Upstream sort (new, relevance, ...).
-- searches.time_filter: Upstream time filter (hour, day, week, month, year, all).
-- searches.enabled: Run by the collector when 1.
-- searches.last_run_at: Epoch seconds of the last execution.
-- searches.status: Outcome of the last execution (ok or an error class).
-- subreddits.pk: Surrogate key.
-- subreddits.workspace_pk: Owning workspace.
-- subreddits.name_lower: Lower-cased display name; unique within the workspace.
-- subreddits.display_name: Display name as Reddit capitalises it.
-- subreddits.subreddit_id: Reddit fullname (t5_...), set once validated; unique within the workspace.
-- subreddits.subreddit_type: Upstream enum stored raw (public, restricted, private, ...).
-- subreddits.subscribers: Subscriber count at last validation.
-- subreddits.over18: Subreddit is marked NSFW upstream.
-- subreddits.quarantine: Subreddit is quarantined upstream.
-- subreddits.enabled: Polled by the collector when 1; discovered-only rows are 0.
-- subreddits.comment_mode: How comment trees are harvested for this source (default full).
-- subreddits.added_at: Epoch seconds when the row was added.
-- subreddits.watermark_created_utc: Max created_utc seen in the last complete sweep (informational).
-- subreddits.last_complete_poll_at: Epoch seconds of the last sweep that reached known territory.
-- subreddits.status: Derived source status; see SUBREDDIT_STATUSES.
-- subreddits.last_error: Last error message; cleared when a run succeeds.
-- subreddits.consecutive_failures: Failed sweeps in a row; reset to 0 on success.
-- subreddits.gap_suspected_at: Epoch seconds when a sweep hit the 1000-item cap before known posts.
-- theme_rules.pk: Surrogate key.
-- theme_rules.theme_pk: Owning theme.
-- theme_rules.rule_group: match, exclude or only_in (the plan's 'group').
-- theme_rules.kind: keyword, regex, flair or subreddit.
-- theme_rules.pattern: The keyword, regex, flair text or subreddit name.
-- theme_rules.scope: title, body, comments or any.
-- theme_rules.case_sensitive: Match case when 1.
-- theme_rules.whole_word: Keyword matches whole words.
-- theme_rules.enabled: Applied when tagging if 1.
-- themes.pk: Surrogate key.
-- themes.workspace_pk: Owning workspace.
-- themes.name: Human-readable name; unique within the workspace.
-- themes.slug: URL slug used at /t/{slug}; unique within the workspace.
-- themes.color: UI colour token or hex.
-- themes.description: What the theme captures.
-- themes.enabled: Applied when tagging if 1.
-- themes.rules_hash: Hash of the enabled rules; a change triggers a full retag.
-- themes.tagged_hash: rules_hash that produced the current post_themes rows.
-- ui_state.key: State key.
-- ui_state.value: State value (text).
-- ui_state.updated_at: Epoch seconds of the last write.
-- workspaces.pk: Surrogate key.
-- workspaces.slug: URL slug and stable identity (e.g. premiere).
-- workspaces.name: Human-readable name.
-- workspaces.description: What the workspace is for.
-- workspaces.ranking: Top-issue ranking rule for digests and theme pages.
-- workspaces.digest_settings_json: Per-workspace digest settings as JSON (sections, thresholds, timezone).
-- workspaces.created_at: Epoch seconds when the workspace was created.
